### ISSUE TITLE
invalid tag in /_layouts/default.html

### ISSUE THREAD

**Issue by NanaVan** [desiredpersona/minimal-jekyll-theme#2]
The tag `include_cached` on line 50 in `/_layouts/default.html` is not a [recognized Liquid tag](https://jekyllrb.com/docs/variables/).
It will lead to a failure for building Github page.

I really appreciate your theme. Hope the bug will be fixed.

**Comment by desiredpersona** [comment]
The `include_cached` tag is used with this Jekyll plugin to cache the rendering of Liquid includes
https://github.com/benbalter/jekyll-include-cache

I wrote about the plugin here if you're interested
https://forestry.io/blog/how-i-reduced-my-jekyll-build-time-by-61/

If you want to use this theme with Github pages I suggest to build the site locally and upload your `_site` folder until v1.0 release.

**Comment by NanaVan** [comment]
Many thanks for your introduction to the plugin. 
With your kindly suggestions, I built the site locally successfully.
